# Generated by Django 4.2.2 on 2024-07-29 11:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_post_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('msg_content', models.TextField()),
                ('msg_time', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
