# Generated by Django 4.2.2 on 2024-07-29 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='room',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
